# Generated by Django 2.0.7 on 2018-07-05 08:43

import django_lifecycle
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('password_updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.LifecycleModelMixin, models.Model),
        ),
    ]
