# Generated by Django 2.0.7 on 2018-07-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='storage',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='', verbose_name='内容详情'),
        ),
    ]
