# Generated by Django 2.0.7 on 2018-07-14 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180706_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('-created',), 'verbose_name': '版本管理', 'verbose_name_plural': '版本管理'},
        ),
    ]
