# Generated by Django 2.0.7 on 2018-07-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(default='', verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(default='', max_length=255, verbose_name='主题'),
        ),
    ]
